# 118b8825-e6de-4c10-8ec2-e3d5614c1e1f
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
    - run: pnpm install
    - run: pnpm run build --if-present
    - run: pnpm test
      env:
        CI: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
      - run: pnpm install
      - run: pnpm run build --if-present
      - run: if [ $(pnpm view $(node -p "require('./package.json').name") version) != $(node -p "require('./package.json').version") ]; then pnpm publish ; fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
